---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d781dca0c598b001135c00e/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: config
  templates:
  - config
- type: document
  path: data/menu.yml
  label: Menu Configuration
  templates:
  - menu
- type: document
  path: data/footer.yml
  label: Footer Configuration
  templates:
  - footer
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content
  label: Page
  create: all
  match: "**/*"
  exclude: "{_index.md,elements.md}"
  templates:
  - page
- type: document
  path: content/elements.md
  label: Elements
  templates:
  - elements
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.47'
