---
label: Action
hide_body: true
display_field: label
fields:
- type: text
  name: label
  label: Button Label
  description: The text displayed inside the action button
  config:
    required: true
- type: text
  name: url
  label: Button URL
- type: boolean
  name: is_scrolly
  label: Is Scrolly
  description: Gives the button a scroll animation (if the button url is a section
    ID)
  default: false
- type: boolean
  name: is_primary
  label: Is Primary
  description: Gives the button a primary color scheme
  default: false
